In [27]:
import sys
import numpy as np 

print(sys.version)
data1 = [1,2,3,4,5]
print(data1,type(data1))


3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
[1, 2, 3, 4, 5] <class 'list'>


### 기본 정보 얻기

dtype : 데이터 타입구하기  
shape : 데이터 구성 형식


In [36]:

arr1 = np.array(data1)

# print(np.shape(arr1))
print( f'array length use shape value  {arr1.shape[0]} ')
print( f'array length use len {len(arr1)} ')

print(arr1,type(arr1))
print(f'data type : {arr1.dtype}')


array length use shape value  5 
array length use len 5 
[1 2 3 4 5] <class 'numpy.ndarray'>
data type : int64


### 데이터 형 변환
astype()  

In [37]:

_arr1 = arr1.astype(np.float)
print(_arr1)
print(_arr1.dtype)



[1. 2. 3. 4. 5.]
float64


In [9]:


#배열로 만들기 
_ary3 = np.array([1,2,3,4])
_ary4 = np.array([10,11,12,13])

print( type(_ary3) , type(_ary4) )

print(_ary3[0:4]*2) 
print(_ary4[0:4]*2) # 2 곱하기 



<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[2 4 6 8]
[20 22 24 26]


### masking
```
array[조건식] = 마스킹값 
```

In [16]:
#2보다 큰것만 True
print(_ary3 > 2)
print(_ary4[_ary3 > 2])

[False False  True  True]
[12 13]


In [14]:

_ary5 = np.array([20,21,22,23])
_ary6 = np.array(['a','b','c','d'])
_ary6[_ary3 > 2] = '-'

print(_ary6)

['a' 'b' '-' '-']


### copy


In [25]:
_a1 = np.array([1,2,3,4,5,6,7,8,9])
_a2 = np.array([10,11,12,13,14,15,16,17,18,19])

print(_a1)
_a1[2:5] = _a2[3:6]
print(_a1)


[1 2 3 4 5 6 7 8 9]
[ 1  2 13 14 15  6  7  8  9]
