In [1]:
import numpy as np 

print(f'load ok numpy version : {np.__version__}')

load ok numpy version : 1.19.0


## 배열생성

In [2]:
arr1 = np.arange(0,10,1)
print(arr1[:])


[0 1 2 3 4 5 6 7 8 9]


## 기본적인 배열 요소 접근

In [3]:
#첫번째요소
print(arr1[0])
# out : 0

#3번째 요소 
print(arr1[3])
# out : 3

0
3


## 특정위치 요소 접근

In [15]:
# 전체 
print(arr1[:])

# 1~7번째 요소  7번째는 포함하지않음
print(arr1[2:7])




[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]


In [16]:
# 인덳싱은 기준이 0 부터 시작, 앞에 오는 인덱싱은 자기 부터 
print(arr1[0:])
print(arr1[1:])
print(arr1[2:])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [17]:
# 뒤에 오는 인덱싱은 자기 전까지 
print(arr1[0:1])
print(arr1[0:2])
print(arr1[0:3])


[0]
[0 1]
[0 1 2]


## 2차원

In [23]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# 둘은 같다.
print(arr2[1][0]) 
print(arr2[1,0]) 

5
5


In [22]:
#2행의 모든 원소꺼내기 
print(arr2[2,:])

#2열의 모든 원소 꺼내기 
print(arr2[:,2])

# 0,1열의 모든 원소 꺼내기 
print(arr2[:,0:2])

[ 9 10 11 12]
[ 3  7 11]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


## 3차원 

In [24]:
x2 = np.array([
    [[101,131]],
    [[101,237]],
    [[248,237]],
    [[248,131]]
    ])
print(x2)

[[[101 131]]

 [[101 237]]

 [[248 237]]

 [[248 131]]]


In [25]:
print(x2[0]) # 첫번째 배열 원소

print(x2[1,:,:]) # 첫번째 원소 꺼내기 x2[1] 와 같은 결과 


[[101 131]]
[[101 237]]


In [26]:
print(x2[:,0]) 

[[101 131]
 [101 237]
 [248 237]
 [248 131]]


In [28]:
print(x2[:,:,0]) # 1번째 열 원소 만 꺼내기
print(x2[:,:,1]) # 2번째 열 원소 만 꺼내기 

[[101]
 [101]
 [248]
 [248]]
[[131]
 [237]
 [237]
 [131]]


In [37]:
print(x2[:,:,:1])
print(x2[:,:,1:])

[[[101]]

 [[101]]

 [[248]]

 [[248]]]
[[[131]]

 [[237]]

 [[237]]

 [[131]]]


In [38]:

print(x2[0,0])
print(x2[1,0])
print(x2[2,0])




[101 131]
[101 237]
[248 237]
